import * as utils from '@aztec/aztec.js/utils';
console.log('utils:', Object.keys(utils).filter(k => k.toLowerCase().includes('pxe')));
import * as wallet from '@aztec/aztec.js/wallet';
console.log('wallet:', Object.keys(wallet).filter(k => k.toLowerCase().includes('pxe')));
import * as pxe from '@aztec/pxe/client/lazy';
console.log('pxe lazy:', Object.keys(pxe).filter(k => k.toLowerCase().includes('pxe')));
import * as aznode from '@aztec/aztec.js/node';
console.log('node:', Object.keys(aznode).filter(k => k.toLowerCase().includes('pxe')));
import * as pxe2 from '@aztec/pxe/server';
console.log('pxe server:', Object.keys(pxe2).filter(k => k.toLowerCase().includes('pxe')));
