/**
 * Universal scan router — classifies decoded QR / barcode text before handling.
 */

export type ScanRouteType = 'session' | 'wallet' | 'passport' | 'gs1' | 'unknown';

export interface ScanRoute {
  type: ScanRouteType;
  raw: string;
  slug?: string;
  gtin?: string;
  walletAddress?: string;
}

const ETH_ADDRESS_RE = /0x[a-fA-F0-9]{40}/;
// Strict standalone match: the ENTIRE trimmed text is an Ethereum address (nothing else)
const ETH_ADDRESS_STRICT_RE = /^0x[a-fA-F0-9]{40}$/;
const GTIN_RE = /^\d{8,14}$/;

function extractWalletAddress(text: string): string | null {
  const trimmed = text.trim();

  // Case 1: The entire payload IS the address — most common QR format
  if (ETH_ADDRESS_STRICT_RE.test(trimmed)) return trimmed;

  // Case 2: EIP-681 standard URI: ethereum:0x...
  if (trimmed.startsWith('ethereum:')) {
    const addr = trimmed.slice('ethereum:'.length).split(/[?@/]/)[0];
    if (ETH_ADDRESS_RE.test(addr) && ETH_ADDRESS_STRICT_RE.test(addr)) return addr;
  }

  // Case 3: URL with known address params (?address= / ?wallet= / ?to=)
  // Only accepted if it is a valid URL — prevents matching arbitrary text that
  // contains a hex address coincidentally (e.g. GS1 barcodes, random URLs)
  try {
    const url = new URL(trimmed);
    const fromParam =
      url.searchParams.get('address') ||
      url.searchParams.get('wallet') ||
      url.searchParams.get('to');
    if (fromParam && ETH_ADDRESS_STRICT_RE.test(fromParam.trim())) return fromParam.trim();
  } catch {
    /* not a URL — no fallback regex match to prevent spoofing */
  }

  return null;
}

function extractPassportSlug(text: string): string | null {
  const trimmed = text.trim();
  try {
    const url = new URL(trimmed);
    const fromQuery = url.searchParams.get('passport');
    if (fromQuery && /^[a-zA-Z0-9_-]{4,64}$/.test(fromQuery)) return fromQuery;
    const pathMatch = url.pathname.match(/\/passport\/([a-zA-Z0-9_-]{4,64})\/?$/i);
    if (pathMatch?.[1]) return pathMatch[1];
  } catch {
    const pathOnly = trimmed.match(/\/passport\/([a-zA-Z0-9_-]{4,64})\/?$/i);
    if (pathOnly?.[1]) return pathOnly[1];
  }
  return null;
}

function extractGtin(text: string): string | null {
  const trimmed = text.trim();
  try {
    const url = new URL(trimmed);
    const host = url.hostname.toLowerCase();
    if (host.includes('gs1') || host.includes('id.gs1.org')) {
      const segments = url.pathname.split('/').filter(Boolean);
      for (const seg of segments) {
        const digits = seg.replace(/\D/g, '');
        if (GTIN_RE.test(digits)) return digits;
      }
      const gtinParam = url.searchParams.get('gtin') || url.searchParams.get('01');
      if (gtinParam && GTIN_RE.test(gtinParam.replace(/\D/g, ''))) {
        return gtinParam.replace(/\D/g, '');
      }
    }
    if (url.pathname.match(/^\/01\/(\d{8,14})/)) {
      const m = url.pathname.match(/^\/01\/(\d{8,14})/);
      if (m?.[1]) return m[1];
    }
  } catch {
    const digits = trimmed.replace(/\D/g, '');
    if (GTIN_RE.test(digits) && digits.length >= 8) return digits;
  }
  return null;
}

function isSessionQr(text: string): boolean {
  const trimmed = text.trim();
  try {
    const url = new URL(trimmed);
    const uuid = url.searchParams.get('uuid') || url.searchParams.get('session');
    const pub  = url.searchParams.get('pub')  || url.searchParams.get('ekey');
    // Legacy long format: uuid + pub embedded in URL
    if (uuid && pub) return true;
    // Legacy long format: /connect or /mobile-kyc path with uuid
    if ((url.pathname.includes('/connect') || url.pathname.includes('/mobile-kyc')) && uuid) return true;

    // ── SHORT FORMAT (generated by qr-init): /connect?s=<uuid> ──
    // The desktop ConnectPage calls /api/auth/qr-init to store the ephemeral
    // pub key server-side and only puts a short UUID (`s` param) in the QR.
    // This is the PRIMARY format used in production — must be detected here.
    const shortUuid = url.searchParams.get('s');
    if (
      shortUuid &&
      (url.pathname.includes('/connect') || url.pathname.includes('/mobile-kyc')) &&
      // Looser validation to allow crypto.randomUUID OR base36 timestamps (Date.now().toString(36))
      /^[0-9a-z-]{6,36}$/i.test(shortUuid)
    ) {
      return true;
    }
  } catch {
    /* fall through */
  }
  try {
    const parsed = JSON.parse(trimmed);
    if (parsed?.uuid && (parsed?.ephemeralPub || parsed?.pub)) return true;
  } catch {
    /* not JSON */
  }
  return false;
}

export function parseScanPayload(decodedText: string): ScanRoute {
  const raw = decodedText.trim();
  if (!raw) return { type: 'unknown', raw };

  if (isSessionQr(raw)) {
    return { type: 'session', raw };
  }

  const wallet = extractWalletAddress(raw);
  if (wallet) {
    return { type: 'wallet', raw, walletAddress: wallet };
  }

  const slug = extractPassportSlug(raw);
  if (slug) {
    return { type: 'passport', raw, slug };
  }

  const gtin = extractGtin(raw);
  if (gtin) {
    return { type: 'gs1', raw, gtin };
  }

  return { type: 'unknown', raw };
}

export function passportPublicUrl(slug: string, origin?: string): string {
  const base = origin || (typeof window !== 'undefined' ? window.location.origin : 'https://www.humanidfi.com');
  return `${base.replace(/\/$/, '')}/passport/${slug}`;
}
