#!/bin/bash
set -euo pipefail

echo "=== Inspeccionando estructura de aztec-up ==="
ls -la "$HOME/"
echo ""
echo "~/.aztec estructura:"
ls -la "$HOME/.aztec/" 2>/dev/null || echo "~/.aztec NO EXISTE"
echo ""
echo "Buscando nargo en todo el home:"
find "$HOME" -name "nargo" -type f 2>/dev/null || echo "nargo no encontrado"
echo ""
echo "Buscando aztec binary en todo el home:"
find "$HOME" -name "aztec" -type f 2>/dev/null | head -10 || echo "aztec no encontrado"
echo ""
echo "PATH actual:"
echo "$PATH"
echo ""
echo "nargo en PATH:"
which nargo 2>/dev/null || echo "nargo NO está en PATH"
echo "aztec en PATH:"
which aztec 2>/dev/null || echo "aztec NO está en PATH"
