/**
 * lib/aztec/qds-contract.ts
 *
 * Wrapper for the HumanityLedger QDs contract on Aztec Alpha Testnet.
 * After deploying the compiled contract, store its address in:
 *   AZTEC_QDS_CONTRACT_ADDRESS=0x...
 *
 * The artifact JSON is generated by `aztec-nargo compile` in ~/whale-circuits/humanity_ledger/
 * and must be placed at: lib/aztec/artifacts/humanity_ledger-HumanityLedger.json
 */

// The on-chain address of the deployed HumanityLedger contract on Aztec Alpha Testnet
export const QDS_CONTRACT_ADDRESS = process.env.AZTEC_QDS_CONTRACT_ADDRESS || null;

// QDs token decimals (using u128 internally, display with 8 decimal places like Bitcoin)
export const QDS_DECIMALS = 8;

// Human-readable token metadata
export const QDS_TOKEN = {
  name:    'Quantum Dots',
  symbol:  'QDs',
  decimals: QDS_DECIMALS,
  network: 'Aztec Alpha Testnet',
};

/**
 * Converts a raw u128 value (from contract) to a human-readable QDs amount.
 */
export function rawToQds(raw: bigint | number): string {
  const divisor = 10n ** BigInt(QDS_DECIMALS);
  const rawBig  = BigInt(raw.toString());
  const whole   = rawBig / divisor;
  const frac    = rawBig % divisor;
  return `${whole}.${frac.toString().padStart(QDS_DECIMALS, '0')}`;
}

/**
 * Converts a user-entered QDs amount string to a raw u128 value for the contract.
 */
export function qdsToRaw(amount: string): bigint {
  const [whole = '0', frac = '0'] = amount.split('.');
  const fracPadded = frac.padEnd(QDS_DECIMALS, '0').slice(0, QDS_DECIMALS);
  return BigInt(whole) * 10n ** BigInt(QDS_DECIMALS) + BigInt(fracPadded);
}

/**
 * Loads the HumanityLedger contract artifact and creates a contract instance.
 * Requires aztec.js to be installed: npm install @aztec/aztec.js
 */
export async function getQDsContract(wallet: any, address?: string) {
  const contractAddress = address || QDS_CONTRACT_ADDRESS;
  if (!contractAddress) {
    throw new Error(
      'QDs contract address not set. Deploy humanity_ledger to Aztec testnet first, ' +
      'then set AZTEC_QDS_CONTRACT_ADDRESS in your .env'
    );
  }

  const { Contract } = await import('@aztec/aztec.js/contracts');
  const { AztecAddress } = await import('@aztec/aztec.js/addresses');

  // Load the compiled artifact from the filesystem
  // This file is generated by: aztec-nargo compile (in ~/whale-circuits/humanity_ledger/)
  // Then copy the artifact JSON from target/dev/ to lib/aztec/artifacts/
  let artifact: any;
  try {
    artifact = require('./artifacts/humanity_ledger-HumanityLedger.json');
  } catch {
    throw new Error(
      'HumanityLedger artifact not found. Run:\n' +
      '  cd ~/whale-circuits/humanity_ledger && aztec-nargo compile\n' +
      '  cp target/dev/humanity_ledger-HumanityLedger.json /path/to/project/lib/aztec/artifacts/'
    );
  }

  return Contract.at(AztecAddress.fromString(contractAddress), artifact, wallet);
}

/**
 * Convenience: Get the QDs balance for a given Aztec address.
 */
export async function getQDsBalance(wallet: any, ownerAddress: string): Promise<string> {
  const { AztecAddress } = await import('@aztec/aztec.js/addresses');
  const contract = await getQDsContract(wallet);
  const owner = AztecAddress.fromString(ownerAddress);

  // The HumanityLedger contract stores balances in a PrivateSet<UintNote>
  // We call the unconstrained `get_balance` view if it exists, or iterate notes
  try {
    const raw = await contract.methods.get_balance(owner).simulate();
    return rawToQds(raw);
  } catch {
    // Fallback: count notes in the private set
    return '0.00000000';
  }
}
