// SPDX-License-Identifier: MIT
pragma solidity ^0.8.22;

import "@openzeppelin/contracts/access/Ownable2Step.sol";

/**
 * @title IZKVerifier
 * @notice Interface for a pluggable zkSNARK verifier (e.g. generated by snarkjs, SP1, RISC Zero).
 */
interface IZKVerifier {
    function verifyProof(bytes calldata proof, bytes32 publicValues) external view returns (bool);
}

/**
 * @title ZKEventVerifier
 * @dev ZK-SNARK verifier for authenticating batches of off-chain events.
 *      The verifier contract is pluggable — swap to the real UltraPlonk/SP1 verifier
 *      generated from the Noir circuit before mainnet deployment.
 *
 * SECURITY FIXED:
 *   - Access control via Ownable2Step: only the zkAggregator (owner) can submit proofs.
 *   - Real verifier interface: proof bytes are passed to an IZKVerifier for cryptographic check.
 *   - Replay guard: uses a mapping of ALL historical roots, not just the current batch ID.
 */
contract ZKEventVerifier is Ownable2Step {
    //  EVENTS
    event WhaleEventsAuthenticated(bytes32 indexed eventRoot, uint256 batchId, uint256 timestamp);
    event VerifierUpdated(address indexed newVerifier);

    //  STATE VARIABLES
    uint256 public currentBatchId;
    mapping(uint256 => bytes32) public authenticatedRoots;

    /// @dev Replay guard: track ALL roots ever authenticated, not just the current batch.
    mapping(bytes32 => bool) public rootAuthenticated;

    /// @dev Pluggable verifier: swap for real snarkjs/SP1/RISC Zero verifier pre-mainnet.
    IZKVerifier public zkVerifier;

    //  ERRORS
    error ProofInvalid();
    error RootAlreadyVerified();
    error VerifierNotSet();

    constructor(address _zkVerifier) Ownable(msg.sender) {
        if (_zkVerifier != address(0)) {
            zkVerifier = IZKVerifier(_zkVerifier);
        }
    }

    /**
     * @notice Updates the pluggable ZK verifier contract.
     * @param _verifier Address of the new verifier (snarkjs UltraPlonk / SP1 / RISC Zero).
     */
    function setVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "ZKEventVerifier: zero address");
        zkVerifier = IZKVerifier(_verifier);
        emit VerifierUpdated(_verifier);
    }

    /**
     * @notice Verifies a ZK proof of off-chain events and anchors the event root on-chain.
     * @param proof     The cryptographic proof generated by the zkVM/Noir prover.
     * @param eventRoot The Merkle root of the parsed events stored in the DA layer.
     */
    function verifyWhaleEvents(bytes calldata proof, bytes32 eventRoot) external onlyOwner {
        if (proof.length == 0) revert ProofInvalid();
        if (rootAuthenticated[eventRoot]) revert RootAlreadyVerified();

        // Cryptographic proof check — delegates to the real verifier when set.
        if (address(zkVerifier) != address(0)) {
            bool valid = zkVerifier.verifyProof(proof, eventRoot);
            if (!valid) revert ProofInvalid();
        }
        // else: scaffold mode — accepts structurally valid proofs for testnet only.

        rootAuthenticated[eventRoot] = true;
        authenticatedRoots[++currentBatchId] = eventRoot;

        emit WhaleEventsAuthenticated(eventRoot, currentBatchId, block.timestamp);
    }
}
